# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# =============================================================================
# ClaimGuard AI - CodeRabbit Configuration
# AI-powered code review for insurance claim adjudication system
# =============================================================================

# Language for reviews
language: "en-US"

# Enable early access features for best AI capabilities
early_access: true

# =============================================================================
# Review Settings
# =============================================================================
reviews:
  # Profile: "chill" = helpful suggestions, "assertive" = strict enforcement
  profile: "assertive"
  
  # Request changes on critical issues (security, bugs)
  request_changes_workflow: true
  
  # Generate high-level summary of changes
  high_level_summary: true
  
  # Include poem (fun for hackathon!)
  poem: true
  
  # Show review status in PR
  review_status: true
  
  # Keep walkthrough expanded (easier to read)
  collapse_walkthrough: false
  
  # Auto-review settings
  auto_review:
    enabled: true
    # Review draft PRs too (useful during development)
    drafts: true
    # Ignore test files for speed
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"

# =============================================================================
# Chat Settings
# =============================================================================
chat:
  # Enable auto-reply to questions
  auto_reply: true
